spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  hikari:
   connection-timeout: 30000  # Timeout para a conexão
   max-lifetime: 60000  # Tempo máximo para uma conexão ser mantida no pool
   maximum-pool-size: 10  # Número máximo de conexões no pool
   idle-timeout: 30000  # Timeout para conexões ociosas


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
